### ISSUE TITLE
SegmentedButton not displaying properly on iOS

### ISSUE THREAD

**Issue by Troto** [XAM-Consulting/FreshEssentials#10]
Hi, I'm having an issue using the SegmentedButtonGroup. When using it on iOS the text in the selected button in the group will not show up using default colours. There is no background on the selected button in iOS and so white text just doesn't show up. This isn't the default behaviour for a segmented button.

**Comment by jessejiang0214** [comment]
Hi Troto,

Did you call  new FreshEssentials.iOS.AdvancedFrameRendereriOS(); in AppDelegate?
https://github.com/XAM-Consulting/FreshEssentialsSample/blob/master/iOS/AppDelegate.cs#L18

**Comment by Troto** [comment]
Oh yes that was it! Thank you!

**Comment by Troto** [comment]
@jessejiang0214 Do you know if there is a way to use the default colours of the platform? At the moment I would like different colours for each platform.
