### ISSUE TITLE
BindablePicker not show the selected item in Android(xamarin.forms)

### ISSUE THREAD

**Issue by huangjinshe** [XAM-Consulting/FreshEssentials#13]
I'm using Xamarin.Forms v2.3.1.114. and FreshEssentials 2.1.0
I'm using Visual Studio debug with Android emulator.  as you see in the picture the selected item not show in the BindablePicker.  
UWP all fine. this only show on in Android .

There is a picture:
![x](https://cloud.githubusercontent.com/assets/3822799/17836985/377c0a64-67d9-11e6-841c-e68704ef0f85.png)

**Comment by jessejiang0214** [comment]
Fixed 1f2479a202d96da2c8ad2cd582c8e1a482594991
