### ISSUE TITLE
The BindablePicker backgound is mess in Android.

### ISSUE THREAD

**Issue by huangjinshe** [XAM-Consulting/FreshEssentials#14]
As you see the background is very mess, like a lot of pieces from other place.

I test the Android Phone and Table on the simulator, all same. (UWP all fine)

There are some pictures:

![1](https://cloud.githubusercontent.com/assets/3822799/17837007/c941abe8-67d9-11e6-9de8-e185802312fc.jpg)
![2](https://cloud.githubusercontent.com/assets/3822799/17837009/ce41323a-67d9-11e6-86bc-191cba19dd4d.jpg)
![3](https://cloud.githubusercontent.com/assets/3822799/17837010/d150e3bc-67d9-11e6-9cb5-37a5956599dd.jpg)

**Comment by rid00z** [comment]
Does this happen in the normal Xamarin.Forms picker?

**Comment by huangjinshe** [comment]
@rid00z , Picker from Android has same problems in Xamarin.Forms

**Comment by rid00z** [comment]
So we can assume this is a Xamarin.Forms issue?

**Comment by huangjinshe** [comment]
@rid00z  I think so.  I report the bug : https://bugzilla.xamarin.com/show_bug.cgi?id=43656

Thank you.
