### ISSUE TITLE
Error in Android and iOS

### ISSUE THREAD

**Issue by erportico** [XAM-Consulting/FreshEssentials#15]
Hi guys, 
I have a problem when I try to bind. The error is:

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

I can't understand why. I copied your example code but I read the values from SQLite and then I created a list of element.

Thank you in advance,

**Comment by rid00z** [comment]
This could actually be anything. It could be something to do with your code. 

Can you isolate this to determine where the issue is and provide some steps to reproduce please?

**Comment by erportico** [comment]
If I execure only one page with this control, the specific error is

> System.IO.FileNotFoundException: Could not load file or assembly 'FreshEssentials.BindablePicker' or one of its dependencies

I don't know what I have to add in references. I added System.Reflections, System.Linq and so on.

**Comment by rid00z** [comment]
You need to add this to your FinishedLaunching event. 
new FreshEssentials.iOS.AdvancedFrameRendereriOS();

We will fix this in a update soon.

**Comment by erportico** [comment]
Thank you!
