### ISSUE TITLE
Error while using FreshEssentials controls

### ISSUE THREAD

**Issue by TheGreatOldOne** [XAM-Consulting/FreshEssentials#16]
Hey,

So, i just added FreshEssentials via Nuget and included it in my view(1). And it is fine, even intellisense helping me when i`m trying to add BindablePicker (2)

Problem starts when i am deploying app to emulator, i am getting following error(for some reason i can not copy exceptions from Xamarin Studio):
Xamarin.Forms.Xaml.XamlParseException has been thrown
Position 27:6 Type controls:BindablePicker not found in xmlns clr-namespace:FreshEssentials;assembly:FreshEssentials

Exception is pretty clear but intellisense seems to see all controls while editing xaml so i have to assume that error lays somewhere else.

Any ideas?
I`m using Xamarin Studio with w10.

1`xmlns:controls = "clr-namespace:FreshEssentials;assembly:FreshEssentials"`
2`<controls:BindablePicker ItemsSource="{Binding searchTypeList, Mode = TwoWay}" SelectedItem="{Binding selectedSearchType, Mode = TwoWay}" />`

/edit: I am running only Android project. Can not check if it is working on IOS for now.

**Comment by jessejiang0214** [comment]
it should be xmlns:fe="clr-namespace:FreshEssentials;assembly=FreshEssentials" 

'assembly=FreshEssentials' not 'assembly:FreshEssentials'

**Comment by TheGreatOldOne** [comment]
Thanks for answer!
Hm it must happen in the process of trying resolve this issue. Anyway, gave me another exception:
System.IO.FileNotfoundException has been thrown
Could not load file or assembly 'FreshEssentials' or one of its dependencies.

Yet, i just menaged to make it working. Had to add reference in Droid project to FreshEssentials.dll
My question now is: Should i did it at first? Do i need add reference manually every time or?

**Comment by jessejiang0214** [comment]
Yes, you should install the nuget package for all projects, PCL, Droid and iOS.
