### ISSUE TITLE
Setting AdvancedFrame.WidthRequest = 100 on constructor prevents to use it when you need it to fit it's content

### ISSUE THREAD

**Issue by ederbond** [XAM-Consulting/FreshEssentials#17]
Let's supose you have a label that needs to be involved by a frame with rounded corners.
Since you are setting the frame WidthRequest = 100 on AdvancedFrame's contructor, it prevents the frame to auto ajust its with base on the value of its content (chield element);
Please stop to set this property on AdvancedFrame constructor.

Try the example below.
The original Xamarin.Forms Frame fits the label correctly while the AdvancedFrame doesn't...

`
<Frame Padding="5,2,5,2" HorizontalOptions="Center"  Style="{StaticResource badge}" HasShadow="False">
              <Label Text="AA" Style="{StaticResource badge-text}"  />
            </Frame>
            <fe:AdvancedFrame CornerRadius="10" Corners="all" OutlineColor="{StaticResource blue-dark-1}" HasShadow="False" >
              <Label Text="AA" />
            </fe:AdvancedFrame>
`

**Comment by jessejiang0214** [comment]
Fixed b41977b5eb1660d23982d2c0e8e67cf0db783812

**Comment by ederbond** [comment]
Thanks a lot guys.
