### ISSUE TITLE
BindablePicker appearance

### ISSUE THREAD

**Issue by leo-mck** [XAM-Consulting/FreshEssentials#19]
I was using an older FreshEssentials on my project that I compiled from code. Today I updated to the nuget version and I noticed that the BindablePicker lookis different but I do not know why. Here is an screenshot of a Xamarin Picker and the BindablePicker:

![image](https://cloud.githubusercontent.com/assets/876986/19350004/610633ec-912c-11e6-9435-004e77d8013f.png)

I would like the BindablePicker to look like the Picker. What defines the appearance of this control?

**Comment by jessejiang0214** [comment]
Sorry about that, we change BindablePicker based on Button, the old one is based on Entry. 

If you still want to use the old one, you can copy are PCL code in your project. 
https://github.com/XAM-Consulting/FreshEssentials/blob/master/src/FreshEssentials/Controls/BindablePicker.cs
