### ISSUE TITLE
Odd build issue with FreshEssentials

### ISSUE THREAD

**Issue by chasd00** [XAM-Consulting/FreshEssentials#20]
Somethings really odd about the iOS linker and FreshEssentials but it probably applies to other assemblies too. Unless I add a 'x:Name='picker'" to the BindablePicker xaml when I run my code in the iphone simulator the FreshEssentials assembly is not included and I get basically a class not found runtime exception ( i come from the Java world ) however I get no error when the File Generator runs. I don't know if there's some meta data you can add to the assembly to tell the linker "hey include me no matter what" or if that's outside the scope of the assembly.

**Comment by jessejiang0214** [comment]
Did you init FreshEssentials in iOS project?
"To init Fresh Essentials on iOS, add the following line to your AppDelegate.cs:

new FreshEssentials.iOS.AdvancedFrameRendereriOS();
"
