### ISSUE TITLE
Text color in IPAD same as background color

### ISSUE THREAD

**Issue by micuentadecasa** [XAM-Consulting/FreshEssentials#25]
Hi, the picker is not working on IPAD, it seems that the textcolor is the same as background. I have tried to change it with Control.SetTitleColor (UIKit.UIColor.Black, UIControlState.Normal ); but no luck.

**Comment by jessejiang0214** [comment]
I cannot reproduce this issue in sample project https://github.com/XAM-Consulting/FreshEssentialsSample 

In that sample, the ItemsSource should be bindable, click "Change Source of Picker" button will show different source.

**Comment by micuentadecasa** [comment]
So late Jesse. Thanks for all.
