### ISSUE TITLE
AdvencedFrame rounded corners not working

### ISSUE THREAD

**Issue by LeoJHarris** [XAM-Consulting/FreshEssentials#31]
Hi seems like your advanced frame corners is not quite working properly setting this in xaml is just making a hard edge corners rectangle (taken from from samplecode):

```
<freshEssentials:AdvancedFrame Corners="all" CornerRadius="30" InnerBackground="Gold" OutlineColor="Red" HorizontalOptions="Center" WidthRequest="200">
                  <Label Text="Corners is All CornerRadius is 30" />
              </freshEssentials:AdvancedFrame>
```

Perhaps its from a recent update of xamarin forms

**Comment by GrantBCU** [comment]
As a temporary workaround, you can specify the CornerRadius in the code-behind for the xaml file and it works.

**Comment by michelmoorlag** [comment]
I have the same issue. Would be nice if we could set corner radius in xaml.

**Comment by brswan** [comment]
Same issue as well.  Specifying the CornerRadius in code behind does not work for me either.
Using .NET Standard, not PCLS

Xamarin Forms v2.4.0.38779
.NET Standard v1.4
