### ISSUE TITLE
Selected value

### ISSUE THREAD

**Issue by robmcleish** [XAM-Consulting/FreshEssentials#32]
It would be nice to have another property so that we can display something different in the drop down after selection. Ie right now i am setting DisplayProperty to a composite property which combines a code and a name like USD - US Dollar. However, after selection i only want to see the value which is USD. Similar to how a web select list works.

**Comment by jessejiang0214** [comment]
I don't think this is a necessary feature for a bindable picker, you can achieve this via key-value array.
