### ISSUE TITLE
error display example bindablepicker

### ISSUE THREAD

**Issue by learsixela** [XAM-Consulting/FreshEssentials#37]
i can`t display the picker in mi app Droid, download the code and fails the same (BindablePickerExample) , does not display the screen, only IOs.

Can you help me, thanks

**Comment by jessejiang0214** [comment]
You need to click "Change source of Picker" button first.

**Comment by learsixela** [comment]
@jessejiang0214 
the example does not even show the screen with the aforementioned button, your answer is not correct, I am deploying in VS for mac.
