### ISSUE TITLE
Make Segmented Button List Bindable

### ISSUE THREAD

**Issue by jimnorth55** [XAM-Consulting/FreshEssentials#7]
I am trying to dynamically populate the list of segmented buttons in the SegmentedButtonGroup control. Being able to bind to an observable would be the ideal solution.  Being able to configure the button list from code would work as well.

**Comment by YsFred4** [comment]
You can actually add buttons from code now.  I just tested this with one of mine and removed all of the buttons from my XAML.  Then I added these commands and it worked perfectly.

buttonGroup.SegmentedButtons.Add(new FreshEssentials.SegmentedButton { Title = "First" });
buttonGroup.SegmentedButtons.Add(new FreshEssentials.SegmentedButton { Title = "Second" });
buttonGroup.SegmentedButtons.Add(new FreshEssentials.SegmentedButton { Title = "from code" });

I do like the idea of it being bindable, but this will get you pretty much what you want.
