### ISSUE TITLE
BindablePicker - BindableProperty Deprecated. Do not use

### ISSUE THREAD

**Issue by StanleyBroo** [XAM-Consulting/FreshEssentials#8]
https://developer.xamarin.com/api/type/Xamarin.Forms.BindableProperty/

**Comment by YsFred4** [comment]
I have a Pull request in to fix these for the SegmentedButtonGroup.  I could always just fix it in the Picker as well.

**Comment by YsFred4** [comment]
I added a pull request from my Fork to put the changes for all of the classes.
